### ISSUE TITLE
Wrong highlighting for multiline strings

### ISSUE THREAD

**Issue by paulovap** [skozlovf/Sublime-QML#7]
See QML file as example:

https://github.com/qt-labs/qml-presentation-system/blob/master/examples/tutorial/SlideDeck.qml

**Comment by ratijas** [comment]
Multiline double-quoted strings is a custom Qt/QML extension to the JavaScript syntax standard, introduced long before backticks (template string literals) were introduced to ECMAScript. As such they can not be parsed with vanilla JS syntax rules.

Fixed in https://github.com/ratijas/Sublime-QML/commit/8ec712f009db04f3c9bfe3ff36826e39aa30b542

Will be an auto-fix once my branch replaces the current approach and gets published.
